- .gitignore
- README.md
- src/cu/edu/cujae/graphy/core/DefaultGraphBuilder.java
- src/cu/edu/cujae/graphy/core/DefaultNotDirectedEdgeFactory.java
- test/cu/edu/cujae/graphy/tests/LocalTests.java
@JavierMarrero @SnowBlackQueen me puedo unir? :)
> .gitignore modified for supporting VS Code and Readme.md updated

- src/cu/edu/cujae/graphy/core/AbstractGraph.java
- src/cu/edu/cujae/graphy/core/AbstractGraphIterator.java
- src/cu/edu/cujae/graphy/core/AdjacencyListGraph.java
- src/cu/edu/cujae/graphy/core/Graph.java
- src/cu/edu/cujae/graphy/core/GraphIterator.java
This commit adds basic iterators, but it is still work in progress. The commit was performed to merge changes from @cdrobaina01's commit.
> Developed basic iterators

- src/cu/edu/cujae/graphy/core/AbstractGraph.java
- src/cu/edu/cujae/graphy/core/AbstractGraphIterator.java
- src/cu/edu/cujae/graphy/core/AdjacencyListGraph.java
- src/cu/edu/cujae/graphy/core/DefaultNode.java
- src/cu/edu/cujae/graphy/core/DefaultSimpleGraph.java
- src/cu/edu/cujae/graphy/core/Graph.java
- src/cu/edu/cujae/graphy/core/GraphIterator.java
- test/cu/edu/cujae/graphy/tests/SimpleGraphTest.java
This commit implements the Depth-First Traversal iterator, allowing to begin the implementation of some algorithms.
> Implemented Depth-First Traversal of a graph via iterators.

- src/cu/edu/cujae/graphy/algorithms/AbstractAlgorithm.java
- src/cu/edu/cujae/graphy/algorithms/Algorithm.java
- src/cu/edu/cujae/graphy/algorithms/CycleDetection.java
- test/cu/edu/cujae/graphy/tests/algorithms/CyclesTest.java
- test/cu/edu/cujae/graphy/tests/algorithms/DijkstraTest.java
Discarded previous implementation of Dijkstra since weighted graphs are not allowed yet, but added a
simple (yet not completely working) implementation of a cycle detection algorithm that showcases all
the implementation of generic algorithms.
> Implemented cycle detection algorithm for undirected graphs

- src/cu/edu/cujae/graphy/algorithms/DijkstraShortestPath.java
- src/cu/edu/cujae/graphy/core/Node.java
- src/cu/edu/cujae/graphy/core/Tree.java
- src/cu/edu/cujae/graphy/core/TreeNode.java
- src/cu/edu/cujae/graphy/core/defaults/DefaultNode.java
- src/cu/edu/cujae/graphy/core/iterators/AbstractGraphIterator.java
- src/cu/edu/cujae/graphy/core/trees/AbstractTree.java
- src/cu/edu/cujae/graphy/core/trees/AbstractTreeNode.java
- src/cu/edu/cujae/graphy/core/trees/DefaultGeneralTreeNode.java
- test/cu/edu/cujae/graphy/tests/algorithms/DijkstraTest.java
In preparation for the implementation of the Kruskal's and Prim's algorithms, a Tree and TreeNode
interface has been added, as well as some utility implementations.
> Added Tree and TreeNode interfaces.

- nbproject/project.properties
- src/cu/edu/cujae/graphy/algorithms/ExistSimpleRoad.java
- src/cu/edu/cujae/graphy/algorithms/TreeDetection.java
- test/cu/edu/cujae/graphy/tests/algorithms/SimpleRoadTest.java
- test/cu/edu/cujae/graphy/tests/algorithms/TreeDetectionTest.java
Este commit es un commit de prueba para comprobar que Github funciona. 😉
> Commit de prueba

- newhtml.html
- src/cu/edu/cujae/graphy/algorithms/Dial.java
- src/cu/edu/cujae/graphy/algorithms/Kosaraju.java
> Problemas técnicos xD

- nbproject/project.properties
- src/cu/edu/cujae/graphy/algorithms/BridgeFinderAlgorithm.java
- src/cu/edu/cujae/graphy/core/Graph.java
- src/cu/edu/cujae/graphy/core/abstractions/AdjacencyListGraph.java
- src/cu/edu/cujae/graphy/core/trees/DefaultGeneralTree.java
- test/cu/edu/cujae/graphy/tests/algorithms/BridgeFinderTest.java
Finished adding and testing algorithm to find bridges in connected undirected graphs.
> Finished the bridge finding algorithm for undirected graphs.

- lib/nblibraries.properties
- src/cu/edu/cujae/graphy/algorithms/BellmanFordShortestPath.java
- test/cu/edu/cujae/graphy/tests/algorithms/BellmanFordTest.java
Incorporación de los cambios hechos por @Amy-Mendez
> Merge development into main

- src/cu/edu/cujae/graphy/algorithms/DijkstraShortestPath.java
- src/cu/edu/cujae/graphy/algorithms/GirvanNewmanAlgorithm.java
- src/cu/edu/cujae/graphy/core/Graph.java
- src/cu/edu/cujae/graphy/core/abstractions/AbstractGraph.java
- src/cu/edu/cujae/graphy/core/utility/Graphs.java
- src/cu/edu/cujae/graphy/utils/Matrix2d.java
- test/cu/edu/cujae/graphy/tests/algorithms/GivanNewmanAlgorithmTest.java
- Added Givan-Newman algorithm
- Finished Dial Shortest Path algorithm
- Finished Kosaraju's Strongly Connected Components algorithm
- Added node removal
- Added graph transposition
- Enhanced documentation
> Minor changes and updates

- src/cu/edu/cujae/graphy/algorithms/FordFulkersonAlgorithm.java
- src/cu/edu/cujae/graphy/core/Graph.java
- src/cu/edu/cujae/graphy/core/Node.java
- src/cu/edu/cujae/graphy/core/abstractions/AbstractGraph.java
- src/cu/edu/cujae/graphy/core/abstractions/AdjacencyListGraph.java
- src/cu/edu/cujae/graphy/core/defaults/DefaultNode.java
- src/cu/edu/cujae/graphy/core/defaults/DefaultWeightedGraph.java
- src/cu/edu/cujae/graphy/core/exceptions/InvalidKeyException.java
- src/cu/edu/cujae/graphy/core/iterators/AbstractGraphIterator.java
- src/cu/edu/cujae/graphy/core/iterators/GraphIterator.java
- src/cu/edu/cujae/graphy/core/trees/DefaultGeneralTreeNode.java
- src/cu/edu/cujae/graphy/core/utility/Graphs.java
- test/cu/edu/cujae/graphy/tests/algorithms/FordFulkersonTest.java
Changes:
- Added disconnection method to the Graph interface.
- Added a new exception: InvalidKeyException
- Finished correction of the bug in the FordFulkersonAlgorithm class
- Added utility methods for checking adjacency.
> Updates, bug corrections and fixups.

- nbproject/project.properties
- src/cu/edu/cujae/graphy/core/Tree.java
- src/cu/edu/cujae/graphy/core/trees/DefaultGeneralTree.java
- test/cu/edu/cujae/graphy/tests/TreeTest.java
Changes:
- Now it is easier to insert in a tree since add returns a `TreeNode<?>`.
> Integration into development

- src/cu/edu/cujae/graphy/algorithms/EulerianCycleDetection.java
- test/cu/edu/cujae/graphy/tests/EulerianCycleDetectionTest.java
Agregué las clases EulerianCycleDetection.java y su test.
> Development césar fernández

- src/cu/edu/cujae/graphy/algorithms/BoruvkaMinimalTree.java
- src/cu/edu/cujae/graphy/algorithms/DinicAlgorithm.java
- test/cu/edu/cujae/graphy/tests/algorithms/BoruvkaAlgorithmTest.java
- test/cu/edu/cujae/graphy/tests/algorithms/DinicAlgorithmTest.java
con el objetivo de hallar un árbol de expansión mínimo y el flujo máximo, respectivamente.
*Fueron creados sus respectivos casos de prueba.
> Clases creadas para los algoritmos de Boruvka y Dinic

- src/cu/edu/cujae/graphy/algorithms/AbstractAlgorithm.java
- src/cu/edu/cujae/graphy/algorithms/KargerMinimumCut.java
- src/cu/edu/cujae/graphy/core/Tree.java
- src/cu/edu/cujae/graphy/core/trees/DefaultGeneralTree.java
- src/cu/edu/cujae/graphy/core/trees/DefaultGeneralTreeNode.java
- test/cu/edu/cujae/graphy/tests/TreeTest.java
- test/cu/edu/cujae/graphy/tests/algorithms/KargerMinimumCutTest.java
Changes:
- Added Karger's Minimum Cut algorithm
> Karger Minimum Cut

- src/cu/edu/cujae/graphy/algorithms/ShortestPathUnweightedGraph.java
- test/cu/edu/cujae/graphy/tests/algorithms/ShortestPathUnweightedGraphTest.java
> Algoritmo ShortestPathUnweightedGraph <3

- nbproject/project.properties
- src/cu/edu/cujae/graphy/core/Graph.java
- src/cu/edu/cujae/graphy/core/Weight.java
- src/cu/edu/cujae/graphy/core/abstractions/AbstractGraph.java
- src/cu/edu/cujae/graphy/core/abstractions/AbstractWeight.java
- src/cu/edu/cujae/graphy/core/iterators/AbstractGraphIterator.java
- src/cu/edu/cujae/graphy/core/iterators/GraphIterator.java
- src/cu/edu/cujae/graphy/core/utility/Graphs.java
- src/cu/edu/cujae/graphy/utils/AbstractTuple.java
- src/cu/edu/cujae/graphy/utils/HashTuple.java
- test/cu/edu/cujae/graphy/tests/ForeachTest.java
- test/cu/edu/cujae/graphy/tests/TupleTest.java
Changes:
- Modified base interfaces.
- Redefined behiavor for Weight generic interface
- Redefined implementation for the hash tuple interface
> Integration of unstable changes

- src/cu/edu/cujae/graphy/algorithms/BronKerboschAlgorithm.java
- test/cu/edu/cujae/graphy/tests/algorithms/BiconnectivityDetectionTest.java
- test/cu/edu/cujae/graphy/tests/algorithms/BronKerboschTest.java
- test/cu/edu/cujae/graphy/tests/algorithms/ConnectivityDetectionTest.java
Algoritmo Bron-Kerbosch para determinar cliques en grafos no dirigidos máximos añadido.
> Development amaya delgado

- src/cu/edu/cujae/graphy/algorithms/DynamicConnectivity.java
- src/cu/edu/cujae/graphy/algorithms/NumberCiclyesKLenght.java
- test/cu/edu/cujae/graphy/tests/algorithms/DynamicConnectivityTest.java
- test/cu/edu/cujae/graphy/tests/algorithms/NumberCiclyesKLenghtTest.java
Algunos cambios son:
- Implementacion del algoritmo NumberCiclyesKLenght para determinar la cantidad de ciclos de longitud k a partir de un nodo en un grafo conexo
- Implementación del algoritmo DynamicConnectivity, basado en una estructura de datos que mantiene dinámicamente la información sobre los componentes conectados del gráfico
> Development jose carlos garcia

- src/cu/edu/cujae/graphy/algorithms/BronKerboschAlgorithm.java
- src/cu/edu/cujae/graphy/algorithms/FringeSearchShortestPath.java
- test/cu/edu/cujae/graphy/tests/algorithms/FringeSearchTest.java
Añadido el algoritmo Fringe Search. (Por ahora solo soportado para grafos dirigidos).
> Fringe Search
